description: "Login ke DockerHub"
steps:
  - run:
      name: DockerHub Login
      command: |
        echo "🔐 Logging in to DockerHub ..."

        if [ -z "$DOCKERHUB_USERNAME" ] || [ -z "$DOCKERHUB_TOKEN" ]; then
          echo "❌ DOCKERHUB_USERNAME or DOCKERHUB_TOKEN is not set."
          exit 1
        fi

        if echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin; then
          echo "✅ Successfully logged in to DockerHub as ${DOCKERHUB_USERNAME:0:2}***"
        else
          echo "❌ Failed to log in to DockerHub"
          exit 1
        fi
