description: "Clear & cache config Laravel"
steps:
  - run:
      name: Laravel Optimize
      command: |
        # Clear caches
        echo "Optimizing Laravel application ..."
        docker exec yotta-dashboard php artisan config:clear || echo "⚠️ Failed config:clear"
        docker exec yotta-dashboard php artisan cache:clear || echo "⚠️ Failed cache:clear"
        docker exec yotta-dashboard php artisan route:clear || echo "⚠️ Failed route:clear"
        docker exec yotta-dashboard php artisan view:clear || echo "⚠️ Failed view:clear"
        echo "✅ Laravel optimization complete."

        # Cache again
        echo "Caching Laravel configuration..."
        docker exec yotta-dashboard php artisan config:cache || echo "⚠️ Failed config:cache"
        docker exec yotta-dashboard php artisan route:cache || echo "⚠️ Failed route:cache"
        docker exec yotta-dashboard php artisan view:cache || echo "⚠️ Failed view:cache"
        echo "✅ Laravel caching complete."

        # Display current cache status
        echo "Current Laravel cache status:"
        docker exec yotta-dashboard php artisan config:cache
        docker exec yotta-dashboard php artisan route:cache
        docker exec yotta-dashboard php artisan view:cache
        echo "✅ Cache status displayed."

        # Display Laravel about information
        echo "Displaying Laravel about information..."
        docker exec yotta-dashboard php artisan about || echo "⚠️ Failed to display Laravel about"

        echo "✅ Laravel optimization and caching process completed."