description: "Build Docker Image and Push to Docker Hub"

steps:
  # DockerHub login
  - command: docker-login.yml

  # Build Docker Image
  - run:
      name: Build Docker Image
      command: |
        echo "🚀 Building Docker image..."
        IMAGE_TAG=$(echo ${CIRCLE_TAG} | sed 's/^v//' | tr '/:*' '-' | tr '[:upper:]' '[:lower:]')
        echo "Using image tag: $IMAGE_TAG"
        docker build -t ${DOCKERHUB_REPO}:$IMAGE_TAG -t ${DOCKERHUB_REPO}:latest -f dockerfile .
        echo "✅ Docker image built successfully."

        # Verify image
        docker images -a | grep ${DOCKERHUB_REPO} | grep $IMAGE_TAG && echo "✅ Image exists" || (echo "❌ Image build failed" && exit 1)

  # Push Docker Image
  - run:
      name: Push Docker Image
      command: |
        echo "🚀 Pushing Docker image to Docker Hub..."
        docker push ${DOCKERHUB_REPO}:$IMAGE_TAG
        docker push ${DOCKERHUB_REPO}:latest
        echo "✅ Docker image pushed successfully."